version: '3'

services:
  auth:
    build:
      dockerfile: Dockerfile.development
      context: ./auth
    environment:
      - JWT_ISSUER=http://auth:3001/
      - JWT_AUDIENCE=https://localhost/api
      - YANDEX_CALLBACK=https://localhost/auth/callback
    volumes:
      - ./auth/cache:/appbuild/cache
      - ./auth/src:/appbuild/src
    ports:
      - "8701:3001"

  api:
    build:
      dockerfile: Dockerfile.development
      context: ./api
    environment:
      - JWT_ISSUER=http://auth:3001/
    volumes:
      - ./api/cache:/appbuild/cache
      - ./api/src:/appbuild/src
    ports:
      - "8702:3002"

# docker-compose -f docker-compose.yml -f docker-compose.development.yml up --build

