FROM gradle:7.4-jdk11 AS buildAuth

RUN mkdir /appbuild

COPY . /appbuild

WORKDIR /appbuild

RUN java -jar SetHttpProxyFromEnv.jar

ENV DEVELOPMENT=true

ENV GRADLE_USER_HOME=/appbuild/cache

#ENV ISSUER=https://localhost/

#ENV AUDIENCE=https://localhost/api

CMD ["sh","-c","gradle --no-daemon run & gradle --no-daemon -t build"]
